### ISSUE TITLE
pre-training model "trained_classifier.pickle"?

### ISSUE THREAD

**Issue by lunalulu** [felixchenfy/Realtime-Action-Recognition#1]
hi ,  thanks for your work!
Can you provide the pre-training model "trained_classifier.pickle"?

**Comment by felixchenfy** [comment]
Hello, I've updated the code and added a better README.
The model is in "model/trained_classifier.pickle"
Sorry I didn't see your message ...

**Comment by lunalulu** [comment]
@felixchenfy thanks very much~
