### ISSUE TITLE
train and track 5 joints in head & lstm approach

### ISSUE THREAD

**Issue by jacksonj393** [felixchenfy/Realtime-Action-Recognition#13]
Hi, awesome work! I want to train new data including head joints as well. Please let me know of changes to be done in the code? 
A couple more questions: does this also track sequence of frames with body movements/actions in terms of speed? Have you thought about using rnn/lstm? Thanks a lot :)

**Comment by felixchenfy** [comment]
@jacksonj393 I plan to refactor almost all the code in the next two weeks. 

I computed the pixel speed as part of the feature vector. Maybe RNN is better.

Thank you!

**Comment by felixchenfy** [comment]
@jacksonj393  Hi, I just refactored the code to make it more readable, as well as making the API easier to use. Just for your information. Thanks for the support!
