### ISSUE TITLE
import tensorflow.contrib.tensorrt as trt ModuleNotFoundError: No module named 'tensorflow.contrib.tensorrt'

### ISSUE THREAD

**Issue by li0128** [felixchenfy/Realtime-Action-Recognition#14]
import tensorflow.contrib.tensorrt as trt
ModuleNotFoundError: No module named 'tensorflow.contrib.tensorrt'
What should I do ?  Thank you !

**Comment by saimj7** [comment]
@li0128 might be a version conflict.. comment the code line and check?

**Comment by li0128** [comment]
@saimj7  linux tf2.0 can run , but  erro in windows with tf2.0 .

**Comment by felixchenfy** [comment]
@li0128 Hi, I only tested on Ubuntu 18. I can't help with it. Good luck!

**Comment by li0128** [comment]
@felixchenfy The project you have done is very good ! Thank you !
