### ISSUE TITLE
Do you have a similar problem ? Report an error and the action recognition ends .

### ISSUE THREAD

**Issue by li0128** [felixchenfy/Realtime-Action-Recognition#15]
![bug](https://user-images.githubusercontent.com/16174528/67457151-71a0bc80-f665-11e9-8b54-3ca37b312dd8.png)

**Comment by li0128** [comment]
![bug3](https://user-images.githubusercontent.com/16174528/67472846-4f6a6700-f684-11e9-86d9-0f3202a9d9d0.png)
The output video is mirrored left and right .

**Comment by li0128** [comment]
ungrade opencv  solved the error 1

**Comment by felixchenfy** [comment]
看起来你解决了问题了...

**Comment by felixchenfy** [comment]
Hi, I just refactored the code to make it more readable, as well as making the API easier to use. Just for your information. Thanks for the support!
