### ISSUE TITLE
No module named 'utils.lib_images_io

### ISSUE THREAD

**Issue by lktinh2018** [felixchenfy/Realtime-Action-Recognition#17]
$ python src/s5_test.py --t webcam
Traceback (most recent call last):
  File "src/s5_test.py", line 54, in <module>
    import utils.lib_images_io as lib_images_io
ModuleNotFoundError: No module named 'utils.lib_images_io'

Please help me !

**Comment by saimj7** [comment]
@lktinh2018  did you try $ python src/s5_test.py --data_type webcam

**Comment by felixchenfy** [comment]
@lktinh2018 @saimj7 That's wired... 
In the `s5_test.py`, I used this sentence:
```
    ROOT = os.path.dirname(os.path.abspath(__file__))+"/../"
    sys.path.append(ROOT)
```
So whether or not running from root folder (such as python s5_test.py) should also work.

I really don't know what causes the problem...

**Comment by lktinh2018** [comment]
> @lktinh2018 @saimj7 That's wired...
> In the `s5_test.py`, I used this sentence:
> 
> ```
>     ROOT = os.path.dirname(os.path.abspath(__file__))+"/../"
>     sys.path.append(ROOT)
> ```
> 
> So whether or not running from root folder (such as python s5_test.py) should also work.
> 
> I really don't know what causes the problem...

I don't know exactly issue, but I can workaround by change utils folder name to other name.
I think it's related with special character ??!

**Comment by felixchenfy** [comment]
@lktinh2018 Hi, it's probably because you've added some python path which has a `utils/` folder in it.
    
You can use the command `printenv PYTHONPATH` to check your python paths. And I would suggest removing the paths that are not system paths.

**Comment by lktinh2018** [comment]
@felixchenfy
I don't know why this issue appear. I just check all PATH and I don't see any utils folder.
Can you give me another solution ?
Now, I move all source file to ROOT folder. And everything work well.

Best regards,
Tinh Lam

**Comment by felixchenfy** [comment]
@lktinh2018 Emmm. Sorry, I don't know why...
