### ISSUE TITLE
some issues about data

### ISSUE THREAD

**Issue by CompliceU** [felixchenfy/Realtime-Action-Recognition#2]
Hello, thank you for sharing, I have read your data, I have some questions, you are processing the video data by frame, there will be some frames that are not part of the action, I don’t understand you are How to deal with it, can I replace the data with time series relationship with the collected pictures,thank you @felixchenfy

**Comment by felixchenfy** [comment]
Hi, below are my answers:

Q: "there will be some frames that are not part of the action"
A: There is a file named "valid_images.txt" inside the dataset. It specifies the label of each video clip. So all frames should be part of an action.
I paste part of the file at below so you can check it.

Q: "can I replace the data with time series relationship with the collected pictures"
A: I don't know your project, but I guess you can -- You can try and play with different algorithms that you come up with.

Contents of "valid_images.txt":
jump_03-02-12-34-01-795
52 59
72 79
114 121
134 141
161 169
181 188
236 245
276 284
313 321
331 338
349 356
367 374
385 392
403 409
424 428
441 541

jump_03-12-09-18-26-176
58 680

jump_03-13-11-27-50-720
65 393

kick_03-02-12-36-05-185
54 62
75 84
102 108
128 136
148 156
167 174
194 202
215 223
237 245
260 267
281 288
302 310
330 336
348 355
366 374
391 398
409 416
428 435

kick_03-08-20-32-41-586
49 110
143 196

kick_03-12-09-23-41-176
58 755

kick_03-13-16-18-12-361
71 150
203 237
264 303
309 349

punch_03-12-09-21-27-876
60 858

run_03-02-12-31-47-095
62 403

run_03-12-09-15-25-375
70 760

sit_03-02-12-27-51-085
65 217

sit_03-02-12-28-32-893
74 355

sit_03-12-09-25-43-527
52 836

sit_03-13-16-15-56-861
55 70
90 103
124 156
178 297
318 363
383 413
433 553
575 616
638 673
692 726
746 777
797 827
893 961
980 1005
1024 1059

squat_03-08-20-26-57-195
75 785

squat_03-13-13-21-48-761
41 293

stand_03-08-20-24-55-587
55 520

stand_03-08-20-35-06-287
60 500

stand_03-12-09-17-05-376
35 395

stand_03-12-09-17-05-376
481 619

stand_03-13-13-22-37-869
40 335

walk_03-12-09-13-10-875
60 800

walk_03-02-12-30-23-393
124 602

wave_03-08-20-28-39-387
65 995

wave_03-13-13-23-25-262
47 354

**Comment by CompliceU** [comment]
Thank you for your answer, I have seen the video segmentation you gave, I don’t know if there is a standard for this interval, such as at least how many frames, or other quantity requirements, thank you very much.

**Comment by felixchenfy** [comment]
No standard. I thought this was correct, so I labeled it in this way.

**Comment by CompliceU** [comment]
Hello, I have preprocessed with the data you provided, and the following problem has occurred:
  File "src/scripts/skeletons_info_generator.py", line 40, in <module>
    skeleton = skeletons[idx_person]
    IndexError: list index out of range
I don't know what caused it. Do you have such a problem in the process of processing? @felixchenfy   thank you

**Comment by felixchenfy** [comment]
No problem on my laptop.

Since idx_person=0, the error "IndexError: list index out of range" indicates that the list is empty. Maybe there is some problem with path settings.

This script simply reads a bunch of .txt files, and put their contents into another .txt file. I believe you can easily debug it ....

**Comment by CompliceU** [comment]
hello,are you Chinese?@felixchenfy

**Comment by felixchenfy** [comment]
恩

**Comment by CompliceU** [comment]
你好，不知道可以加一下你其他的联系方式请教一些问题吗？非常感谢了，1215533585@qq.com @felixchenfy

**Comment by felixchenfy** [comment]
已加qq

**Comment by huwade** [comment]
Hello

what does the number behind the action mean ? 
for example  sit_03-12-09-25-43-527, what does 03-12-09-25-43-527 those number mean ?

thanks

**Comment by felixchenfy** [comment]
> Hello
> 
> what does the number behind the action mean ?
> for example sit_03-12-09-25-43-527, what does 03-12-09-25-43-527 those number mean ?
> 
> thanks

@huwade Hi, It's the time that I recorded the images: 2019 March 12th, 9 am, 25 minutes, 43 seconds, 527 milliseconds.

**Comment by huwade** [comment]
thanks
