### ISSUE TITLE
Dose this work be supported by paper?

### ISSUE THREAD

**Issue by jessica-anyen** [felixchenfy/Realtime-Action-Recognition#22]
Thanks for sharing this work, for research purposes, does this  work be supported paper ? If it does, please offer it.

您好:
感謝分享作品，為了列入文獻，想請問這篇作品是否有論文?如果有能否提供下?再麻煩了

**Comment by felixchenfy** [comment]
Hi, this is just a course project. No paper.  
Thanks

**Comment by jessica-anyen** [comment]
thanks for reply~
