### ISSUE TITLE
  Program running speed

### ISSUE THREAD

**Issue by GuodongFan** [felixchenfy/Realtime-Action-Recognition#24]
In the first time, the program runs about 10-15 fps. However, I do not know what i did. The program runs 5-11fps (i just reinstall numpy). My GPU is RTX 2080 ti and I use cmu 656x368.

**Comment by felixchenfy** [comment]
@GuodongFan Sorry I don't know ...

**Comment by GuodongFan** [comment]
找到原因了，pip安装的tensorflow比conda安装的效率低； 也是我conda安装了一次，用pip更新了numpy的版本。

**Comment by felixchenfy** [comment]
@GuodongFan 酷啊. 谢谢分享bug原因.
