### ISSUE TITLE
`ValueError: n_components=100 must be between 0 and min(n_samples, n_features)=16 with svd_solver='full'

### ISSUE THREAD

**Issue by jessica-anyen** [felixchenfy/Realtime-Action-Recognition#25]
i am trying to training a new pose, i run the s4_train.py, but i got the error message below:
`ValueError: n_components=100 must be between 0 and min(n_samples, n_features)=16 with svd_solver='full'`

about number of data:
`After train-test split:
Size of training data X:     (16, 314)
Number of training samples:  16
Number of testing samples:   8`

where can i change the number of n_components? or is there another way to solve it? Please reply.

我嘗試訓練一個新的姿勢，在跑s4_train.py時出現了以下錯誤訊息:
`ValueError: n_components=100 must be between 0 and min(n_samples, n_features)=16 with svd_solver='full'`

有關於資料的數量
`After train-test split:
Size of training data X:     (16, 314)
Number of training samples:  16
Number of testing samples:   8`

請問應該從哪裡調整 n_components的數量，或有無其他解決方法?再麻煩回覆了

**Comment by felixchenfy** [comment]
Hi, you have only 16 training samples, which is smaller than the n_components=100, and this causes the error. 

I think it would be better if you can collect more data. 

Or, you may change the `n_components` to a value smaller than 16 (The relevant code snippet is shown below with n_components highlighted).
![image](https://user-images.githubusercontent.com/22253529/69062407-7cd6d600-09e0-11ea-9cc7-c4eeb5f42e84.png)  
(utils/lib_classifier.py)

**Comment by jessica-anyen** [comment]
thanks for your help, i solve this by modify the "settings"
![image](https://user-images.githubusercontent.com/53212447/69139238-0f6b9800-0afb-11ea-8bf9-c87201a340b4.png)
