### ISSUE TITLE
ValueError: non-broadcastable output operand with shape (1,) doesn't match the broadcast shape (2,)

### ISSUE THREAD

**Issue by jessica-anyen** [felixchenfy/Realtime-Action-Recognition#26]
i'm trying to train a new pose, i resize my video as 640x480, but it shows error message below when i run the s5_test.py:

`ValueError: non-broadcastable output operand with shape (1,) doesn't match the broadcast shape (2,)`

![image](https://user-images.githubusercontent.com/53212447/69341227-213c6f00-0ca4-11ea-933b-0d58c6c6624c.png)

Does anyone who also have this problem? what does this mean?How to solve it?

我正嘗試訓練一個新的姿勢，我將我的影片調整成640x480，但在我執行s5_test.py時仍出現問題:

`ValueError: non-broadcastable output operand with shape (1,) doesn't match the broadcast shape (2,)`

請問有遇過這個問題嗎? 這是代表甚麼問題?我應該怎麼解決?

**Comment by felixchenfy** [comment]
您好, 我感觉是设置的类别数有问题. 
能看下你的config/config.yaml文件吗?

**Comment by jessica-anyen** [comment]
thanks for your reply, the picture below is the config.yaml, i only train for one pose "dab", does it cause the error?
感謝您的回覆，下圖是我的config內容，我只訓練"dab"這個動作。請問是否無法僅訓練一個動作?

![image](https://user-images.githubusercontent.com/53212447/69521507-21858480-0f9a-11ea-915d-1579866f66ab.png)

**Comment by felixchenfy** [comment]
> thanks for your reply, the picture below is the config.yaml, i only train for one pose "dab", does it cause the error?
> 感謝您的回覆，下圖是我的config內容，我只訓練"dab"這個動作。請問是否無法僅訓練一個動作?
> 
> ![image](https://user-images.githubusercontent.com/53212447/69521507-21858480-0f9a-11ea-915d-1579866f66ab.png)

对的,最少需要两个类别, 比如 `dab` 和`others`.  
数据越丰富越好. 如果我的数据和你的类别不一样的话, 你可以把我的那些数据当others来训练.  
祝好!

**Comment by jessica-anyen** [comment]
thanks for your help! it works!
感謝協助，使用兩個類別就能運作了
