### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'model/trained_classifier.pickle'

### ISSUE THREAD

**Issue by heavenluv** [felixchenfy/Realtime-Action-Recognition#32]
![Capture](https://user-images.githubusercontent.com/58972570/70977836-a96a3480-20e9-11ea-80df-e02e0bd6236e.PNG)
 I don't know why I get this error when I'm using the webcam as a preference, the cv2 windows just opened for 5 seconds then closed, mostly just show nothing and the progress goes not responsive.
Anyways I did put the pickle file inside the model and it's definitely inside so I don't know what's wrong with that.

**Comment by felixchenfy** [comment]
您好, 应该是相对路径的问题:
如果你在目录 `X` 下运行了某个python程序, 设置的模型的路径是一个相对路径 `model_path=model/trained_classifier.pickle`,那么
`with open(model_path, 'rb')` 这句话就会试图去打开 `X/model/trained_classifier.pickle`.

解决办法:
要么把相对路径改为绝对路径: 例如`model_path=C:/Users/model/trained_classifier.pickle`, 要么在合适的目录下运行程序

**Comment by heavenluv** [comment]
好的我已经解决了 谢谢！
