### ISSUE TITLE
Why it can't recognize all the people?

### ISSUE THREAD

**Issue by jessica-anyen** [felixchenfy/Realtime-Action-Recognition#38]
![Deepin 截圖_選取範圍_20200202115825](https://user-images.githubusercontent.com/53212447/73636166-39673c00-46a0-11ea-820b-d391516556d2.png)

According to the picture, it seems that people P5, P6 can be recognized clearly, but why their actions can not be defined?(I've trained for the class "UseComputer")

Also, I figure out that it doesn't perform well when there is more than 4 people in the same frame, how can I modify that?

如圖，人P5,P6 的骨骼節點應該算辨識得蠻清楚的, 但是為何他們的動作沒有被辨識出來?(我已有訓練"使用電腦"這個類別的動作)

同樣的，我發現當同一畫面/場景中有多於4人出現時，效果似乎不太好，我應該怎麼修改才能應用於多人的狀況呢?

**Comment by felixchenfy** [comment]
您好, 很抱歉的说, 我的项目无法实现您图片里的分类. 
以下是我的分析和建议.

## 分析:

您图片里的几个类别(比如 思考,交谈, 用电脑), 人的姿态都是坐着然后手上干一些事情 ---- 只凭借人的骨骼位置是很难区分的. 需要更高级的深度学习算法, 通过处理整张图片(而不是骨骼), 才能做识别. 

我这是一个课程项目, 算法比较简易, 只根据人的骨骼位置做机器学习和分类. 
如果您也是做课程项目的话, 可以参考我的; 但如果是用到实际场景, 我这个项目很可能是不行的.

## 建议:  
您要实现的这个分类功能, 得试试这两年发表的顶会论文的算法. 
但即使是那些算法, 估计也很难做到("动作识别"学术圈还没有成熟的算法). 我觉得您可能起码需要一个研发小组才能实现要求.

## 其他:  
另外, P5,P6我没有显示结果的原因是, 我人为的做了几个设定:"(1) 如果人的下肢没有被检测到, 就不进行分类; (2) 如果人在图片中比较小, 就不进行分类".
我做这个设定的原因是, 我这个项目的分类效果太差了. 缺失腿部或者人太小时, 识别基本就是错的, 所以我索性就不做识别了.

很抱歉不能帮到你. 祝你好运!

**Comment by jessica-anyen** [comment]
thanks for your reply, though you said that this works doesn't perform well, i still appreciate for your effort and answering me these questions! 

感謝您的回覆與建議!
