### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by burhanuddin78** [felixchenfy/Realtime-Action-Recognition#44]

**Comment by felixchenfy** [comment]
Hi,
    In your screenshot, `src/s2*.py` reads in 0 data, which is supposed to
be generated by `src/s1*.py`.
    So I guess you didn't set up the images and their labels properly.
Please see 5. Training data
<https://github.com/felixchenfy/Realtime-Action-Recognition#5-training-data>
section.
Thanks!



Burhanuddin Imran <notifications@github.com> 于2020年3月14日周六 上午11:54写道：
