### ISSUE TITLE
Quetion ： google.protobuf.message.DecodeError: Unexpected end-group tag.

### ISSUE THREAD

**Issue by FFFD-iona** [felixchenfy/Realtime-Action-Recognition#48]
Thanks for share so interting work . 
I can definitely works on the tf-pose-estition .
But when I am doing the step train on the data set : run the "python  src/s1_get_skeletons_from_training_imgs.py" it was told the error .
Is the version of tensorflow wrong ?(By the way ,my version is 1.12.0 for the limitation of GPU ) 
I am looking for a lot of answers but did not solve it , could you please ? 
Thank you a lot !

**Comment by felixchenfy** [comment]
Hi, I really can't help with the TensorFlow version problem. I used to struggle a long time to figure out my own environment, and I really lack the knowledge about it.

Good luck to you!
