### ISSUE TITLE
Problem when running run.py Issue

### ISSUE THREAD

**Issue by oguchi-ebube** [felixchenfy/Realtime-Action-Recognition#50]
I keep getting this issue whenever i run this script

lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libnvinfer.so.5: cannot open shared object file: No such file or directory

**Comment by felixchenfy** [comment]
Looks like a TensorFlow error. Sorry, I don't know that.

**Comment by oguchi-ebube** [comment]
Already resolved it. But thanks

**Comment by oguchi-ebube** [comment]
If you are using Colab and you run into this issue. Just install the requirement below:
!sudo apt-get install -y --no-install-recommends libnvinfer5=5.1.5-1+cuda10.0 \
    libnvinfer-dev=5.1.5-1+cuda10.0
And you'd be fine.

**Comment by Prithila05** [comment]
How did you run the run.py file for webcam? When I run this I get the error: can't open camera by index 0

**Comment by felixchenfy** [comment]
@Prithila05 About this error "can't open camera by index 0", maybe your webcam has another index, or your webcam is not detected by the program.

I think you will need to debug by yourself and then modify the code to open the camera
