### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by rahulvijaysoans** [felixchenfy/Realtime-Action-Recognition#53]
I checked your code inside 
The code calculates both the keypoints coordinates and some of the joint angles. But only the x,y coordinates of the keypoints are used for the training If i am correct?

**Comment by felixchenfy** [comment]
Yes, correct!  

I tried the angles, but they didn't improve the accuracy, and sometimes even made it worse. These 2D angles are not helpful so I did not use them at last.

(Sorry I didn't check GitHub very often after my graduation)

**Comment by rahulvijaysoans** [comment]
> Yes, correct!
> 
> I tried the angles, but they didn't improve the accuracy, and sometimes even made it worse. These 2D angles are not helpful so I did not use them at last.
> 
> (Sorry I didn't check GitHub very often after my graduation)

**Comment by rahulvijaysoans** [comment]
Thank you for your reply.
