### ISSUE TITLE
How to add other neural network models with least modifications of your work?

### ISSUE THREAD

**Issue by BenoitKAO** [felixchenfy/Realtime-Action-Recognition#55]
Thank you for your marvelous work!

I have already read this issue:
https://github.com/felixchenfy/Realtime-Action-Recognition/issues/46

However, I would like to know how to add other neural network models with the least modifications of your work?
like mobilenet_v2_large, mobilenet_v2_small, mobilenet V1, V2 ,V3, openpose-darknet, YOLO, SSD, vgg-???, resnet-??? ... and so on.

Any help is appreciated.

**Comment by felixchenfy** [comment]
Hi, sorry there are only 2 options... `mobilenet_thin` and `cmu`.

I used the code of this github project `https://github.com/ildoonet/tf-pose-estimation`, which only supports the above two options.
