### ISSUE TITLE
how to cite your work

### ISSUE THREAD

**Issue by Mary-xl** [felixchenfy/Realtime-Action-Recognition#59]
Dear author,
I like your work and hope to improve the work by modifying and changing some components. Just wondering how to cite this piece of work?
Thanks!

**Comment by felixchenfy** [comment]
Hi. Thanks for your interest. But this work has no related publication. 
I don't know either about how to cite this work.

**Comment by Mary-xl** [comment]
Hi Feiyu,
Thank you for your information! We will probably use a different approach but your work is definitely valuable. Have you included this project in your thesis project so we may cite your thesis instead?
Best regards,
Mary

________________________________

**Comment by felixchenfy** [comment]
No, I don't have a thesis....
( sorry I didn't see your message)
