### ISSUE TITLE
Train more than 9 actions

### ISSUE THREAD

**Issue by 4al** [felixchenfy/Realtime-Action-Recognition#6]
Hello and thank you for sharing your work with us! I've successfully managed to run the training with your dataset and the webcam demo, but I've encountered an error after training my own dataset with 19 different actions when running run_detector.py via webcam:

```
Realtime-Action-Recognition/src/mylib/action_classifier.py", line 85, in smooth_scores
score_sums += score
ValueError: operands could not be broadcast together with shapes (9,) (19,) (9,)
```
I've updated the action_labels in run_detector.py, but couldn't find any other declaration code for the number of action classes. I guess this might be a matrix dimension related problem. Could you help me with that?

**Comment by hundanLi** [comment]
You should change the action_labels in run_detector.py before running
```bash
python src/run_detector.py  --source txtscript 
```

**Comment by felixchenfy** [comment]
@4al Hi, did you solve the problem?
The number of action classes is calculated from the names of the training data. 

See src/train.ipynb:
![image](https://user-images.githubusercontent.com/22253529/62845392-732d2c00-bc95-11e9-9853-2ca49a3b76f3.png)

Then copy the labels to the variable `action_labels` in `run_detector.py`, and then the program should work.

Is it possible that your trained model is not saved to disk? Or you load the wrong model?
Please message me if you solved it.
Thanks!

**Comment by 4al** [comment]
Thank you for the advice. That worked!
