### ISSUE TITLE
Training 2 actions

### ISSUE THREAD

**Issue by GyungBin** [felixchenfy/Realtime-Action-Recognition#64]
Hello! Thank you for sharing your work!
There was an error when running s5_test.py via webcam after training its own dataset with two actions.

```
File "C:\Realtime-Action-Recognition-master\utils\lib_classifier.py", line 185, in smooth_scores
    score_sums += score
ValueError: operands could not be broadcast together with shapes (9,) (2,) (9,) 
```

I think it's related to the matrix,
could you help me that?

**Comment by Amyhds** [comment]
Hi! I have the same problem.
how did you solve it?

**Comment by qkdkralsgh** [comment]
@Amyhds Hi! maybe you need to set window_size & classses

**Comment by vpeopleonatank** [comment]
I also faced this issue because I use the original model which is trained for 9 classes, but my new dataset has 6 classes. When run training script at step 4, my model was not saved because the qt error occured before saving model. You should check classes in `config.yaml` file or trained model file.

**Comment by Amyhds** [comment]
```
#classes: ['stand', 'walk', 'run', 'jump', 'sit', 'squat', 'kick', 'punch', 'wave']
classes: ['lying', 'other', 'sitting', 'standing']
```

I changed classes like that in config.yaml but why should I change window_size? Could you tell me why? what else do I have to change?

**Comment by qkdkralsgh** [comment]
@Amyhds If you changed window_size, you need to set window_size.  When training the model, the pca, window_size, and classes must be set well.

**Comment by Amyhds** [comment]
Thanks for the answer!!!
