### ISSUE TITLE
The training image link could not be opened.

### ISSUE THREAD

**Issue by sdustdk1427** [felixchenfy/Realtime-Action-Recognition#8]
Hello, the download link of the training image you provided cannot be opened. Could you please provide another download link?I would like to see how your training images are tagged.Can only use pictures when training?Can I just play video?Or do you have to frame video into pictures?

**Comment by felixchenfy** [comment]
@sdustdk1427 Hi, I just check the [link](https://drive.google.com/file/d/1nBOQDbmJvR2KOtJDpASmXwapbFV-PSrs/view?usp=sharing), and I can open it.  (The data is compressed, so the goolge drive shows that it cannot be previewed, but you should be able to download it. Or maybe you are in an area that cannot visit google drive?)

![image](https://user-images.githubusercontent.com/22253529/66408342-69cdf080-e9b4-11e9-8282-8c8d90722812.png)

About the training data, I first converted a video into images, such as 00001.png, 00002.png, ...
And then, in a txt file, I specify the "Folder name" and "Time slot of each action". The action type is the first word of the folder name. The txt file is shown below:

valid_images.txt
```
jump_03-02-12-34-01-795
52 59
72 79
114 121
134 141
161 169
181 188
236 245
276 284
313 321
331 338
349 356
367 374
385 392
403 409
424 428
441 541

jump_03-12-09-18-26-176
58 680

jump_03-13-11-27-50-720
65 393

kick_03-02-12-36-05-185
54 62
75 84
102 108
128 136
148 156
167 174
194 202
215 223
237 245
260 267
281 288
302 310
330 336
348 355
366 374
391 398
409 416
428 435

kick_03-08-20-32-41-586
49 110
143 196

kick_03-12-09-23-41-176
58 755

kick_03-13-16-18-12-361
71 150
203 237
264 303
309 349

punch_03-12-09-21-27-876
60 858

run_03-02-12-31-47-095
62 403

run_03-12-09-15-25-375
70 760

sit_03-02-12-27-51-085
65 217

sit_03-02-12-28-32-893
74 355

sit_03-12-09-25-43-527
52 836

sit_03-13-16-15-56-861
55 70
90 103
124 156
178 297
318 363
383 413
433 553
575 616
638 673
692 726
746 777
797 827
893 961
980 1005
1024 1059

squat_03-08-20-26-57-195
75 785

squat_03-13-13-21-48-761
41 293

stand_03-08-20-24-55-587
55 520

stand_03-08-20-35-06-287
60 500

stand_03-12-09-17-05-376
35 395

stand_03-12-09-17-05-376
481 619

stand_03-13-13-22-37-869
40 335

walk_03-12-09-13-10-875
60 800

walk_03-02-12-30-23-393
124 602

wave_03-08-20-28-39-387
65 995

wave_03-13-13-23-25-262
47 354


```

**Comment by sdustdk1427** [comment]
那可以麻烦您发我邮箱一份吗？我实在是下载不了。十分感谢！邮箱：1002901024@qq.com

**Comment by felixchenfy** [comment]
qq邮件传2Gb的大文件是不是会有问题啊? 我传百度云吧. 明天传好了回复你

sdustdk1427 <notifications@github.com> 于2019年10月8日周二 上午10:38写道：

**Comment by sdustdk1427** [comment]
好的~谢谢你 对了 我今天一个视频分为801张图片，但是执行python src/run_detector.py时显示只预测了445张图片，这是为什么？当图片有775张时，预测387张图片。

**Comment by felixchenfy** [comment]
你选的 --source 是folder吗?

>

**Comment by felixchenfy** [comment]
def set_source_images_from_folder():
    return CURR_PATH + "../data_test/apple/", 1
SRC_IMAGE_FOLDER, SKIP_NUM_IMAGES = set_source_images_from_folder()

这句话里的SKIP_NUM_IMAGES是指每读一张图片以后,跳过多少张图片再读下一张.或许你是要设置成0?

Feiyu Chen <felixchenfy@gmail.com> 于2019年10月8日周二 上午10:59写道：

> 你选的 --source 是folder吗?
>
>>

**Comment by sdustdk1427** [comment]
是的 明白了 多谢

**Comment by sdustdk1427** [comment]
不能直接跑视频对么 只能分祯成图片检测完再合并成视频？

**Comment by felixchenfy** [comment]
恩对,现在还不能跑视频... 要么文件夹读图片,要么webcam.
我过两周有空的话会加一下这个功能....

sdustdk1427 <notifications@github.com> 于2019年10月8日周二 上午11:04写道：

**Comment by felixchenfy** [comment]
我现在的数据集是以图片的形式保存的, 10k张图有5个G... 以百度云的尿性我觉得你如果没有vip的话可能得下载好几天...

> 图片我正在传:
[image: QQ截图20191009090904.png]

**Comment by sdustdk1427** [comment]
还好我有百度云的vip，谢谢~

**Comment by zjjzjj123** [comment]
@sdustdk1427 我直接将webcam这个调用摄像头的语句，改成了本地的视频文件是可以检测的，只是检测的视频并没有保存到本地。我想加个cv2.write()就应该可以了。

**Comment by felixchenfy** [comment]
@sdustdk1427 @zjjzjj123 hi,我上传好了
https://pan.baidu.com/s/1ef1Q5YqVOrUb_45apRD4cA

**Comment by zjjzjj123** [comment]
> @sdustdk1427 @zjjzjj123 hi,我上传好了
> https://pan.baidu.com/s/1ef1Q5YqVOrUb_45apRD4cA

@felixchenfy 谢谢

**Comment by felixchenfy** [comment]
@zjjzjj123 @sdustdk1427 Hi, 我今天刚更新了整个项目的代码, 使得它更容易阅读和使用. 

数据集的链接我也更新了一下----数据集里的图片 原先是.png,大概6Gb, 太大了; 于是我把图片都改成了.jpg,只有2Gb. 和你们说一声.

谢谢支持!
