### ISSUE TITLE
how to generate valid_images.txt.

### ISSUE THREAD

**Issue by DukeZacharia** [felixchenfy/Realtime-Action-Recognition#88]
Hello, please can anyone help me to know how you made the file {[valid_images.txt](https://github.com/felixchenfy/Realtime-Action-Recognition/blob/master/data/source_images3/valid_images.txt).}

I am trying to add my own dataset.
Thank you in advance

**Comment by SofiV11** [comment]
@DukeZacharia Hello, how did you decide that?

**Comment by DukeZacharia** [comment]
> @DukeZacharia Hello, how did you decide that?

@SofiV11 What do you mean exactly?
if it's about the dataset I managed to solve the issue I had and recorded the video dataset using https://github.com/felixchenfy/record_images_from_usbcam
